config/routes.rb
Rails.application.routes.draw do

  resources :categories, except: [:show]
  resources :containers do
    resources :records, except: [:index, :show] do
      member do
        get :clone
        put :toggle_paid
      end
    end
  end
  devise_for :users

  root "containers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :records

  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end
end

app/models/container.rb
class Container < ApplicationRecord
  belongs_to :user
  has_many :records, dependent: :destroy

  validates :name, presence: true

  def total_expenses
    records.expense.sum(:value)
  end

  def expenses_records_size
    records.expense.size
  end

  def total_income
    records.income.sum(:value)
  end

  def income_records_size
    records.income.size
  end

  def balance
    total_income - total_expenses
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "template", "updated_at", "user_id"]
  end

end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :container

  validates :record_type, presence: true
  validates :value, presence: true
  validates :category_id, presence: true

  enum record_type: { income: 0, expense: 1 }

  def self.ransackable_attributes(auth_object = nil)
    %w(category_id date description paid record_type)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :containers, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :records

  before_create :build_default_category

  private

  def build_default_category
    self.categories.build(name: 'Other')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < DashboardController
  before_action :set_category, only: %i[ edit update destroy ]

  def index
    @q = current_user.categories.ransack(params[:q] || default_ransack_params)
    @categories = @q.result
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      redirect_to categories_url, notice: "Category was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @category.update(category_params)
      redirect_to categories_url, notice: "Category was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @category.records.any?
      redirect_to categories_url, alert: "You cannot delete this category as long as there are records assigned to it."
      return
    end

    @category.destroy

    redirect_to categories_url, notice: "Category was successfully destroyed."
  end

  private
    def set_category
      @category = current_user.categories.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end

    def default_ransack_params
      { s: "name asc" }
    end
end

app/controllers/containers_controller.rb
class ContainersController < DashboardController
  before_action :set_container, only: %i[ show edit update destroy ]
  before_action :set_template_containers, except: %i[index]

  def index
    params[:q] ||= { template_eq: 'false' }

    @q = current_user.containers.order(:date, :id).ransack(params[:q])
    @containers = @q.result
  end

  def show
    @q = @container.records.includes(:category).ransack(params[:q]|| default_records_ransack_params)
    @records = @q.result
  end

  def new
    @container = Container.new
  end

  def edit
  end

  def create
    @container = Container.new(container_params)
    @container.user = current_user

    template_id = params.dig(:template_id)

    if template_id.present?
      template_container = Container.find(template_id)
      template_container.records.each do |record|
        attributes = record.attributes.except("id", "created_at", "updated_at")

        if record.date && (params[:month].present? || params[:year].present?)
          month = params[:month].presence || record.date.month
          year = params[:year].presence || record.date.year

          attributes["date"] = Date.new(year.to_i, month.to_i, record.date.day)
        end

        @container.records.build(attributes)
      end
    end

    if @container.save
      redirect_to container_url(@container), notice: "Container was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @container.update(container_params)
      redirect_to container_url(@container), notice: "Container was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @container.destroy

    redirect_to containers_url, notice: "Container was successfully destroyed."
  end

  private

    def set_container
      @container = current_user.containers.find(params[:id])
    end

    def set_template_containers
      @template_containers = current_user.containers.where(template: true)
    end

    def container_params
      params.require(:container).permit(:name, :date, :template)
    end

    def default_records_ransack_params
      { s: "date asc" }
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index

  end

end

app/controllers/records_controller.rb
class RecordsController < DashboardController
  before_action :set_container, only: %i[ new create edit update destroy toggle_paid clone ]
  before_action :set_record, only: %i[ edit update destroy toggle_paid clone ]

  def index
    @records = @container.records
  end

  def new
    @record = Record.new
  end

  def edit
  end

  def create
    @record = Record.new(record_params)
    @record.user = current_user
    @record.container = @container

    if @record.save
      redirect_to @container, notice: "Record was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @record.update(record_params)
      redirect_to @container, notice: "Record was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @record.destroy

    redirect_to @container, notice: "Record was successfully destroyed."
  end

  def toggle_paid
    @record.update(paid: params[:paid])

    render json: { paid: @record.paid }
  end

  def clone
    @record = @record.dup
  end

  private
    def set_container
      @container = current_user.containers.find(params[:container_id])
    end

    def set_record
      @record = @container.records.find(params[:id])
    end

    def record_params
      params.require(:record).permit(:date, :record_type, :description, :category_id, :value, :paid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def formatted_value(value)
    number_to_currency(value, unit: 'zł', format: "%n %u", precision: 2)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/containers_helper.rb
module ContainersHelper

  def formatted_balance(balance)
    if balance >= 0
      content_tag(:span, "+ #{number_to_currency(balance, unit: 'zł', format: "%n %u")}", class: "text-success")
    else
      content_tag(:span, "- #{number_to_currency(balance.abs, unit: 'zł', format: "%n %u")}", class: "text-danger")
    end
  end

end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_bootstrap_class_for(flash_type)
    case flash_type.to_s
    when "notice" then "success"
    when "alert" then "danger"
    else flash_type.to_s
    end
  end
end

app/helpers/records_helper.rb
module RecordsHelper

  def formatted_record_value(record)
    if record.income?
      content_tag(:span, "+ #{number_to_currency(record.value, unit: 'zł', format: "%n %u")}", class: "text-success")
    else
      content_tag(:span, "- #{number_to_currency(record.value, unit: 'zł', format: "%n %u")}", class: "text-danger")
    end
  end

end

app/views/categories/_category.html.erb
<tr id="<%= dom_id category %>">
  <td><%= category.name %></td>
  <td class="text-end"><%= category.records.size %></td>
  <td>
    <div class="d-flex gap-2 justify-content-center">
      <%= link_to edit_category_path(category), class: "btn btn-sm btn-primary" do %>
        <i class="bi bi-pencil"></i>
      <% end %>
      <%= button_to category, method: :delete, class: "btn btn-sm btn-danger",
        data: {
          controller: "confirm",
          action: "click->confirm#createModal",
          confirm_text: "Are you sure you want to delete this category?"
        } do %>
        <i class="bi bi-trash3"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/categories/_filter.html.erb
<%= search_form_for q, html: {
  data: {
    controller: "filter-form",
    action: "change->filter-form#submitForm",
    filter_form_target: "form"
    }
  } do |f| %>
  <div class="row mb-3">
    <div class="col-3 mb-2">
      <%= f.label :name_cont, "Description Contains" %>
      <div class="input-group">
        <span class="input-group-text"><i class="bi bi-search"></i></span>
        <%= f.text_field :name_cont, class: "form-control", placeholder: "Description Contains" %>
      </div>
    </div>
    <div class="col-3 mb-2 d-flex align-items-end gap-2">
      <%= link_to request.path, class: "btn btn-secondary" do %>
        <i class="bi bi-arrow-counterclockwise"></i> Reset Filters
      <% end %>
    </div>
  </div>

<% end %>

app/views/categories/_form.html.erb
<%= simple_form_for(category) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>

  <div class="mb-3">
    <%= f.button :submit, nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render 'shared/header', header: 'Editing category' do %>
  <%= link_to categories_path, class: "btn btn-secondary" do %>
    <i class="bi bi-arrow-left"></i> Back to categories
  <% end %>
<% end %>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<%= render 'shared/header', header: 'Categories' do %>
  <%= link_to new_category_path, class: "btn btn-success" do %>
    <i class="bi bi-plus"></i> New category
  <% end %>
<% end %>

<%= render 'categories/filter', q: @q %>

<div id="containers">
  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th><%= sort_link @q, :name, "Name" %></th>
        <th class="text-end">Records</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @categories.each do |category| %>
        <%= render category %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/categories/new.html.erb
<%= render 'shared/header', header: 'New category' do %>
  <%= link_to categories_path, class: "btn btn-secondary" do %>
    <i class="bi bi-arrow-left"></i> Back to categories
  <% end %>
<% end %>

<%= render "form", category: @category %>

app/views/containers/_container.html.erb
<tr id="<%= dom_id container %>">
  <td>
    <%= link_to container.name, container %>
    <% if container.template? %>
      <span class="badge bg-secondary">TEMPLATE</span>
    <% end %>
  </td>
  <td><%= container.date.to_date %></td>
  <td class="text-end"><%= formatted_value(container.total_income) %></td>
  <td class="text-end"><%= formatted_value(container.total_expenses) %></td>
  <td class="text-end"><%= formatted_balance(container.balance) %></td>
  <td></td>
</tr>

app/views/containers/_filter.html.erb
<%= search_form_for q, html: {
  data: {
    controller: "filter-form",
    action: "change->filter-form#submitForm",
    filter_form_target: "form"
    }
  } do |f| %>
  <div class="row mb-3">
    <div class="col-3 mb-2">
      <%= f.label :name_cont, "Description Contains" %>
      <div class="input-group">
        <span class="input-group-text"><i class="bi bi-search"></i></span>
        <%= f.text_field :name_cont, class: "form-control", placeholder: "Description Contains" %>
      </div>
    </div>
    <div class="col-3 mb-2">
      <%= f.label :template_eq, "Template", class: "mr-2" %>
      <%= f.select :template_eq,
        [
          ['All', nil],
          ['Template', 'true'],
          ['Not Template', 'false']
        ],
        {},
        class: "form-control"
      %>
    </div>
    <div class="col-3 mb-2 d-flex align-items-end gap-2">
      <%= link_to request.path, class: "btn btn-secondary" do %>
        <i class="bi bi-arrow-counterclockwise"></i> Reset Filters
      <% end %>
    </div>
  </div>

<% end %>

app/views/containers/_form.html.erb
<%= simple_form_for(container) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>

  <%= f.input :date, as: :string, input_html: { type: 'date' } %>

  <%= f.input :template, as: :boolean %>

  <% if container.new_record? %>
    <hr>

    <div class="mb-3">
      <%= label_tag :template_id, "Choose a template", class: "form-label" %>
      <%= select_tag :template_id, options_from_collection_for_select(@template_containers, :id, :name, params[:template_id]), include_blank: 'None', class: "form-control" %>
      <small class="form-text text-muted">This is optional. Select a template if you want.</small>
    </div>

    <div class="row mb-3" >
      <div class="col-6">
        <div>
          <%= label_tag :month, "Month", class: "form-label" %>
          <%= select_tag :month,
            options_for_select((1..12).map { |m| [Date::MONTHNAMES[m], m] }, params[:month]),
            include_blank: 'Select a month',
            class: "form-control" %>
        </div>
      </div>
      <div class="col-6">
        <div>
          <%= label_tag :year, "Year", class: "form-label" %>
          <%= select_tag :year,
            options_for_select([Date.current.year, Date.current.year + 1, Date.current.year + 2], params[:year]),
            include_blank: 'Select a year',
            class: "form-control" %>
        </div>
      </div>
      <small class="form-text text-muted">
        All records from the template will be copied with the selected month and year. If not specified, the original dates will remain unchanged.
      </small>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.button :submit, nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/containers/edit.html.erb
<%= render 'shared/header', header: 'Edit container' do %>
  <%= link_to @container, class: "btn btn-secondary" do %>
    <i class="bi bi-eye"></i> Show this container
  <% end %>
  <%= link_to containers_path, class: "btn btn-secondary" do %>
    <i class="bi bi-arrow-left"></i> Back to containers
  <% end %>
<% end %>

<%= render "form", container: @container %>

app/views/containers/index.html.erb
<%= render 'shared/header', header: "Containers" do %>
  <%= link_to new_container_path, class: "btn btn-success" do %>
    <i class="bi bi-plus"></i> New container
  <% end %>
<% end %>

<%= render 'containers/filter', q: @q %>

<div id="containers">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Date</th>
          <th class="text-end">Income</th>
          <th class="text-end">Expense</th>
          <th class="text-end">Balance</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
          <% @containers.each do |container| %>
            <%= render container %>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/containers/new.html.erb
<%= render 'shared/header', header: 'New container' do %>
  <%= link_to containers_path, class: "btn btn-secondary" do %>
    <i class="bi bi-arrow-left"></i> Back to containers
  <% end %>
<% end %>

<%= render "form", container: @container %>

app/views/containers/show.html.erb
<%= render 'shared/header', header: @container.name do %>
  <%= link_to edit_container_path(@container), class: "btn btn-primary" do %>
    <i class="bi bi-pencil"></i> Edit this container
  <% end %>

  <%= button_to @container, method: :delete, class: "btn btn-danger",
    data: {
      controller: "confirm",
      action: "click->confirm#createModal",
      confirm_text: "Are you sure you want to delete this container?"
    } do %>
    <i class="bi bi-trash3"></i> Destroy this container
  <% end %>

  <%= link_to containers_path, class: "btn btn-secondary" do %>
    <i class="bi bi-arrow-left"></i> Back to containers
  <% end %>
<% end %>

<%= render 'records/index', container: @container, records: @records, q: @q %>

app/views/dashboard/index.html.erb
Welcome

<%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>


    <div class="container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flash_messages' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>


    <div class="container">
      <%= render 'shared/flash_messages' %>
      <div class="row min-vh-100 d-flex justify-content-center align-items-center">
        <div class="col-4 p-4 border rounded">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/records/_filter.html.erb
<%= search_form_for q, url: container, html: {
  data: {
    controller: "filter-form",
    action: "change->filter-form#submitForm",
    filter_form_target: "form"
    }
  } do |f| %>
  <div class="row mb-3">
    <div class="col-3 mb-2">
      <%= f.label :date_gteq, "From Date" %>
      <div class="input-group">
        <span class="input-group-text"><i class="bi bi-calendar-range"></i></span>
        <%= f.date_field :date_gteq, class: "form-control", placeholder: "From Date" %>
      </div>
    </div>
    <div class="col-3 mb-2">
      <%= f.label :date_lteq, "To Date" %>
      <div class="input-group">
        <span class="input-group-text"><i class="bi bi-calendar-range"></i></span>
        <%= f.date_field :date_lteq, class: "form-control", placeholder: "To Date" %>
      </div>
    </div>
    <div class="col-3 mb-2">
      <%= f.label :record_type_eq, "Record Type" %>
      <%= f.select :record_type_eq, Record.record_types.map { |key, value| [key.humanize, value] }, { include_blank: 'All Types' }, { class: "form-select" } %>
    </div>
    <div class="col-3 mb-2">
      <%= f.label :description_cont, "Description Contains" %>
      <div class="input-group">
        <span class="input-group-text"><i class="bi bi-search"></i></span>
        <%= f.text_field :description_cont, class: "form-control", placeholder: "Description Contains" %>
      </div>
    </div>
    <div class="col-3 mb-2">
      <%= f.label :category_id_eq, "Category", class: "mr-2" %>
      <%= f.select :category_id_eq, options_for_select([["All Categories", nil]] + current_user.categories.map { |c| [c.name, c.id] }, q.category_id_eq), {}, { class: "form-select" } %>
    </div>
    <div class="col-3 mb-2">
      <%= f.label :paid_eq, "Paid Status", class: "mr-2" %>
      <%= f.select :paid_eq,
        [
          ['All', nil],
          ['Paid', 'true'],
          ['Unpaid', 'false']
        ],
        {},
        class: "form-control"
      %>
    </div>
    <div class="col-3 mb-2 d-flex align-items-end gap-2">

      <%= link_to request.path, class: "btn btn-secondary" do %>
        <i class="bi bi-arrow-counterclockwise"></i> Reset Filters
      <% end %>
    </div>
  </div>

<% end %>

app/views/records/_form.html.erb
<%= simple_form_for([container, record]) do |f| %>
  <%= f.error_notification %>

  <%= f.input :date, as: :string, input_html: { type: 'date' } %>

  <%= f.input :record_type, collection: Record.record_types.keys.map { |type| [type.humanize, type] }, prompt: 'Select Record Type', selected: record.record_type || (record.new_record? ? 'expense' : nil) %>

  <%= f.input :description, as: :text %>

  <%= f.input :category_id, collection: current_user.categories.order('name asc'), label_method: :name, value_method: :id, prompt: 'Select Category' %>

  <%= f.input :value %>

  <%= f.input :paid, as: :boolean, label: 'Paid' %>

  <div class="mb-3">
    <%= f.button :submit, nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/records/_index.html.erb
<%= render 'records/statistics', container: container, records: records  %>

<div>
  <div class="d-flex justify-content-between align-items-center">
    <h3>Records</h3>

    <%= link_to new_container_record_path(container), class: "btn btn-success" do %>
      <i class="bi bi-plus"></i> New record
    <% end %>
  </div>
</div>
<div>
  <%= render 'records/filter', container: container, q: q %>
</div>

<div id="records">
  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th></th>
        <th>Date</th>
        <th>Description</th>
        <th>Category</th>
        <th>Paid</th>
        <th class="text-end"><%= sort_link q, :value, "Value" %></th>
        <th class="text-center"></th>
      </tr>
      </thead>
      <tbody>
      <% records.each do |record| %>
        <%= render record %>
      <% end %>
      </tbody>
      <tfoot>
      <tr>
        <td colspan="5"></td>
        <td class="text-end"><%= formatted_balance(container.balance) %></td>
        <td></td>
      </tr>
      </tfoot>
    </table>
  </div>
</div>

app/views/records/_record.html.erb
<tr id="<%= dom_id record %>">
  <td>
    <% if record.record_type == "income" %>
      <i class="bi bi-arrow-down-square-fill text-success"></i>
    <% else %>
      <i class="bi bi-arrow-up-square-fill text-danger"></i>
    <% end %>
  </td>
  <td><%= record.date %></td>
  <td><%= record.description %></td>
  <td><%= record.category.name %></td>
  <td>
    <div class="form-check" data-controller="toggle-paid" data-toggle-paid-url="<%= toggle_paid_container_record_path(record.container, record) %>">
      <input class="form-check-input"
             type="checkbox"
             value="<%= record.id %>"
             id="paid_<%= record.id %>"
             <%= 'checked' if record.paid %>
             data-action="change->toggle-paid#toggle"
             data-toggle-paid-target="checkbox">
    </div>
  </td>
  <td class="text-end"><%= formatted_record_value(record) %></td>
  <td>
    <div class="d-flex gap-2 justify-content-center">
      <%= link_to edit_container_record_path(record.container, record), class: "btn btn-sm btn-primary" do %>
        <i class="bi bi-pencil"></i>
      <% end %>
      <%= link_to clone_container_record_path(record.container, record), class: "btn btn-sm btn-secondary" do %>
        <i class="bi bi-copy"></i>
      <% end %>
      <%= button_to container_record_path(record.container, record), method: :delete, class: "btn btn-sm btn-danger",
        data: {
          controller: "confirm",
          action: "click->confirm#createModal",
          confirm_text: "Are you sure you want to delete this record?"
        } do %>
        <i class="bi bi-trash3"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/records/_statistics.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-4">
      <div class="card text-white bg-success mb-3">
        <div class="card-header">Income</div>
        <div class="card-body">
          <h5 class="card-title"><%= formatted_value(container.total_income) %></h5>
          <p class="card-text"><%= container.income_records_size %> records</p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card text-white bg-danger mb-3">
        <div class="card-header">Expenses</div>
        <div class="card-body">
          <h5 class="card-title"><%= formatted_value(container.total_expenses) %></h5>
          <p class="card-text"><%= container.expenses_records_size %> records</p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card bg-light mb-3">
        <div class="card-header">Balance</div>
        <div class="card-body">
          <h5 class="card-title"><%= formatted_balance(container.balance) %></h5>
          <p class="card-text"><%= records.size %> records</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/records/clone.html.erb
<%= render 'shared/header', header: 'Cloning record' do %>
  <%= link_to @container, class: "btn btn-secondary" do %>
    <i class="bi bi-arrow-left"></i> Back to container
  <% end %>
<% end %>

<%= render "form", container: @container, record: @record %>

app/views/records/edit.html.erb
<%= render 'shared/header', header: 'Editing record' do %>
  <%= link_to @container, class: "btn btn-secondary" do %>
    <i class="bi bi-arrow-left"></i> Back to container
  <% end %>
<% end %>

<%= render "form", container: @container, record: @record %>

app/views/records/new.html.erb
<%= render 'shared/header', header: 'New record' do %>
  <%= link_to @container, class: "btn btn-secondary" do %>
    <i class="bi bi-arrow-left"></i> Back to container
  <% end %>
<% end %>

<%= render "form", container: @container, record: @record %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= flash_bootstrap_class_for(message_type) %> alert-dismissible fade show mt-3" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<% header ||= "Page Header" %>

<div class="d-flex justify-content-between align-items-center mt-3">
  <h1><%= header %></h1>
  <div class="d-flex gap-2">
    <%= yield %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary rounded mt-3" aria-label="Thirteenth navbar example">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mobile-menu" aria-controls="mobile-menu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse d-lg-flex" id="mobile-menu">

      <%= link_to root_path, class: 'navbar-brand col-lg-3 me-0' do %>
        Budget App
      <% end %>

      <ul class="navbar-nav col-lg-6 justify-content-lg-center">
        <li class="nav-item">
          <%= link_to "Containers", containers_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link" %>
        </li>
      </ul>
      <div class="d-lg-flex col-lg-3 justify-content-lg-end">
        <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false }, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</nav>